spring:
  application:
    name: analysis-service

app:
  cache:
    maximum-size: 500
    expire-after-access: 10m
  data:
    path: file:/Users/dodge/Documents/Interview/HSBC/hsbc-homework/data/House_Price_Dataset.csv
  prediction-service:
    predict-url: ${PREDICTION_SERVICE_PREDICT_URL:http://localhost:8000/predict}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
